Feat/reservelist
B-I-G-team/big_next pull request #14
Opened 2023-09-09 04:14 UTC by AdolphKim

# What is this PR? 🔍

- 서비스 스펙 : 예약내역

# Changes 📝
- ReserveCard Molecule 및 하위 Molecule 제작
- NavHeader Moldcule 제작
- ReserveInfo 페이지 제작

# Screenshot 📷

| 기능 |                                                    스크린샷                                                     |
| :--: | :-------------------------------------------------------------------------------------------------------------: |
| ReserveInfo 페이지  | ![image](https://github.com/B-I-G-team/big_next/assets/80530044/977736e9-7615-4e4c-87f6-3e64a13c4ddc) |

# Test Checklist ☑️

- [ ] 스토리북 확인
- [ ] 코드 확인

# ETC 📎

2023-09-11 15:10 UTC, daehwan2 requested changes
데이터 구조가 아직 없어서
더미 데이터까지 만든다고 고생하셨습니다~!

우선 완벽히 본건 아니나, 제가 코멘트 단것들 확인해주시고...!

UI는 이쁘게 잘나오는 것 같아 코멘트 단것만 수정되면
머지하겠습니다~~!!

추후 백엔드 api 와 연동시 수정해나가면서 컴포넌트를 다시 잡을 필요는 있어 보입니다..!

2023-09-11 15:10 UTC, daehwan2 commented on components/atom/CustomImage/index.tsx
> +  return <StyledImage width="0" height="0" size={size} src={src} alt={alt} />;
width 와 height 속성은 필요없는거 아닌가요?!

2023-09-11 15:10 UTC, daehwan2 commented on components/atom/buttons/TextButton/index.tsx
>    transition: 200ms;
transition 을 부모 속성에 주니까
제대로 동작안하고 있는걸로 확인이 됩니다!

ButtonText 컴포넌트에 transition 을 주면 정상동작 하네요~!!
ButtonText의 색상이 바뀌고 있어서 그런것 같습니다!

2023-09-11 15:10 UTC, daehwan2 commented on components/atom/inputs/PrimaryInput/index.tsx
> +  width: 300px;
Container 의 width 가 100%가 되어야하는거 아닐까요??

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/NavHeader/index.tsx
> +  };
이건 어떤의미로 작성해주신걸까요?

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/NavHeader/index.tsx
> +    </Container>
pageName 과 onClickBack 속성을 받고 있군요!

해당 컴포넌트에서
<img width="287" alt="image" src="https://github.com/B-I-G-team/big_next/assets/53414542/0a6c7fe3-20a4-4eed-b7b3-ec46ecce95ab">

저장 버튼도 속성값으로 조정할 수 있게하면 어떨까요?

예를들면 `isSaveButton: boolean` 이러한 형식으로 받아서
true일 경우에만 저장 버튼을 보이게 하는방식이요!

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/NavHeader/index.tsx
> +  pageName: string;
onClickBack 속성을 그냥 받으면 되지 않을까요?
어떤의미로 작성해주신건지 궁금합니다.!

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/NavHeader/index.stories.tsx
> +const Template: Story<any> = (args: any) => <NavHeader {...args} />;
타입을 Props로 바꿔주면 좋을 것 같아요~!!

또한 스토리북 작성하실때, 속성이 있는 컴포넌트들은 일부값이라도 넣어서 예시를좀 더많이 만들어 주시면 좋을 것 같아요. 테스트 과정에서 별도의 텍스트를 쳐야지만 확인이 가능하기도 하고, 한번에 파악하기가 힘든 것 같아서요!

인풋 컴포넌트도 마찬가지 입니다! 스토리북에서 보여질때도 신경 써주시면 좋을 것 같아요!

지금 같은 경우는

pageName 속성을 넣은 버젼도 만들어주시면 좋을 것 같아요.

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/ReserveCardHeader/index.tsx
> +  };
이 쪽 콘솔과 reserveKey는 무엇을 의미하는걸까요?

onClickButton 자체를 속성으로 받는게 어떨까요?!

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/ReserveCardMain/index.tsx
> +  };
이부분도 굳이 현재 컴포넌트내에 이렇게 만드신 이유가 있으실까요?

2023-09-11 15:10 UTC, daehwan2 commented on components/page/ReserveInfo/index.stories.tsx
> +const Template: Story<any> = (args: any) => <ReserveInfo {...args} />;
여기도 any로 되어있네요~!

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/ReserveCardMain/index.stories.tsx
> +const Template: Story<any> = (args: any) => <ReserveCardMain {...args} />;
any 발견이요~

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/ReserveCardHeader/index.stories.tsx
> +const Template: Story<any> = (args: Props) => <ReserveCardHeader {...args} />;
any가 있네요~~

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/ReserveCard/index.stories.tsx
> +const Template: Story<any> = (args: any) => <ReserveCard {...args} />;
any가있습니다

2023-09-11 15:10 UTC, daehwan2 commented on components/molecule/ReserveCard/index.tsx
> +  margin-bottom: 10px;
Divider 컴포넌트를 굳이 만드신 이유가 무엇일까요?

ReserveCardHeader 컴포넌트에 border bottom 을 주는건 어떤가요?

해당 Divider 로 인하여 총 헤더와 메인사이의 20px 차이가 나게되네요!

2023-09-11 15:12 UTC, daehwan2 commented
그리고 추가적으로 파일 conflict 가 나네요!! 해결 부탁드립니다~~!!

+ 아 그리고!! PR올리기전에 자기 코드 File changed 를 보면서 시간내서 스스로 리뷰를 한번하고 PR을 올리는 방식을 추천드립니다..! 리뷰하는 사람들도 좋고 서로 좋을 것 같아서요~!!

2023-09-12 11:58 UTC, AdolphKim commented on components/atom/CustomImage/index.tsx
> +  return <StyledImage width="0" height="0" size={size} src={src} alt={alt} />;
뭔가 오류가 생겼어서 넣었었는데, 안넣어도 작동이 잘 되네요 .. 변경하였습니다 !

2023-09-12 12:02 UTC, AdolphKim commented on components/molecule/NavHeader/index.tsx
> +  };
router를 이용해서 전 페이지로 돌아가려는 시도 중에 미쳐 삭제하지 못한 부분인 것 같습니다.

삭제하겠습니다

2023-09-13 04:01 UTC, AdolphKim commented on components/molecule/ReserveCardMain/index.tsx
> +  };
위의 리뷰해주신것과 같이 애초에 카드를 만들때 해당하는 예약정보의 고유 ID값을 받아서 해당 ID 값에 따른 정보를

가져올 수 있게 컴포넌트 내에 함수를 두는게 맞다고 생각합니다. 밖에서 가져오게되면 매개변수로 넣어줘야 할

개수도 많아져 사용성이 떨어지지 않나 생각합니다.

2023-09-13 04:20 UTC, daehwan2 commented on components/molecule/ReserveCardMain/index.tsx
> +  };
음 이부분은 실제 사용할때 선언을 해서 사용하면 좋을것같아요!

굳이 로그를 남기는 함수를 만들어서 테스트코드를 작성할 필요없다고 생각이듭니다.

2023-09-13 04:52 UTC, AdolphKim commented
수정완료 했습니다. 확인 부탁드립니다 !

2023-09-13 05:25 UTC, daehwan2 reviewed
수정된것 까지 확인하였습니다~!! 👍

2023-09-13 05:25 UTC, daehwan2 commented on components/atom/typography/Title1/index.tsx
> +    <Text bold={true} color={color}>
```tsx
<Text bold color={color}>
...
</Text>
```
이런식으로 true 값은 넘길 수 있습니다!!

해당 방식 어떠신가요~!?

2023-09-13 05:25 UTC, daehwan2 commented on components/atom/typography/Title2/index.tsx
> +    <Text bold={true} color={color}>
```tsx
<Text bold color={color}>
...
</Text>
```
이런식으로 true 값은 넘길 수 있습니다!!

해당 방식 어떠신가요~!?

2023-09-13 05:25 UTC, daehwan2 commented on components/atom/typography/SubTitle/index.tsx
> +  line-height: 16px;
SubTitle 컴포넌트도

Title1, Title2 처럼 font weight 처리를

```tsx
<Text bold color={color}>
...
</Text>
```
이런식으로 하면 어떨까요?

2023-09-13 05:25 UTC, daehwan2 commented on components/atom/inputs/PrimaryInput/index.stories.tsx
> +};
오 속성 넣어주시니까 한결 편하게 확인이 가능하네요~!! 👍

2023-09-13 05:25 UTC, daehwan2 commented on components/molecule/NavHeader/index.tsx
> +          <Body3>저장완료</Body3>
이거는 저희 피그마에 보면
저장 으로만 되어 있는것같습니다!

2023-09-13 05:25 UTC, daehwan2 commented on components/molecule/ReserveCardMain/index.tsx
> +  reserveKey: number;
이 값은 안쓰이고 있네요! 확인부탁드립니다

2023-09-13 05:25 UTC, daehwan2 commented on styles/index.ts
> +  }
폰트 적용 정말 수고많으셨습니다~~~ 😀

2023-09-13 08:30 UTC, 98minseok commented on components/molecule/ReserveCardMain/index.tsx
> +  reserveKey: number;
추후 사용될것으로 예상 되어 남겨놓았는데 삭제하는게 좋을까요 ?

2023-09-13 09:08 UTC, daehwan2 commented on components/molecule/ReserveCardMain/index.tsx
> +  reserveKey: number;
네 사용할때 넣는걸로 합시다~~

2023-09-13 09:10 UTC, AdolphKim commented
코드리뷰 모두 적용하였습니다. 확인 부탁드립니다.

2023-09-13 09:24 UTC, daehwan2 approved these changes
수정된것까지 확인하였습니다.

수고많으셨습니다 😀

2023-09-13 09:24 UTC, merged