Feat : 예약 상세내역 페이지 생성
B-I-G-team/big_next pull request #17
Opened 2023-09-13 09:56 UTC by AdolphKim

# What is this PR? 🔍

- 서비스 스펙 : 예약 상세내역 페이지

# Changes 📝
-  TitleAndValue Molecule 제작
-  Drawer Molecule 제작
-  ReserveCardDetail Molecule 제작
-  ReserveDetail Page 제작

# Screenshot 📷

| 기능 |                                                    스크린샷                                                     |
| :--: | :-------------------------------------------------------------------------------------------------------------: |
| ReserveDetail page  | ![image](https://github.com/B-I-G-team/big_next/assets/80530044/198da664-1c24-4597-b508-c1a0b01d4d6e) |
| ReserveCardDetail  | ![image](https://github.com/B-I-G-team/big_next/assets/80530044/0da9f65b-2cd1-47a4-9624-edeb61b74e6b)|
| TitleAndValue |![image](https://github.com/B-I-G-team/big_next/assets/80530044/b62d74c8-25fe-4e54-aea3-6f28eb16f8e3) |

# Test Checklist ☑️

- [ ] 스토리북 확인
- [ ] Drawer 기능 확인

2023-09-14 03:59 UTC, daehwan2 requested changes
점심시간이 끝나가서

리뷰는 우선 여기까지만 하겠습니다!!

수고하셨습니다~!!

(아직 리뷰진행중입니당)

2023-09-14 03:59 UTC, daehwan2 commented on components/atom/typography/Title2/index.tsx
> +  align-items: center;
이부분을 빼고 위에 컴포넌트 렌더링 부분을

```tsx
<Text bold color={color}>{children}</Text>
```

이렇게 바꾸는건 어떨까요?

다른 typography 컴포넌트들은 전부그렇게 되어 있는데
수정하는게 좋을 것 같습니다..!

#14 에서 제대로 코드 리뷰를 하지 못하였네요,,

2023-09-14 03:59 UTC, daehwan2 commented on components/icons/DrawerIcon.tsx
> +        fill-opacity="0.85"
여기 props 값을

fillOpacity로 해야 jsx 문법에 걸리지 않는것 같습니다!

2023-09-14 03:59 UTC, daehwan2 commented on components/molecule/Drawer/index.tsx
> +        </DrawerButton>
<img width="648" alt="image" src="https://github.com/B-I-G-team/big_next/assets/53414542/81ba88ae-d35b-42a6-8e0c-e35811e80dd2">

DrawerButton 은 컴포넌트로 분리하는게 어떨까요?

그리고 cursor:pointer 가 아니네요!

div 보단 button 태그로 선언하는게 의미상 좋을 것 같기도 합니다.!

2023-09-14 03:59 UTC, daehwan2 commented on components/molecule/Drawer/index.tsx
> +        </DrawerButton>
+ 추가적으로 해당 버튼은 펼쳐진 상태면 화살표아이콘이 위로가도록 되어야 합니다.

2023-09-14 04:02 UTC, daehwan2 commented
+ 추가적으로 해당 브랜치는 이전에 작업하던 다른브랜치에서부터 파생된 브랜치 이군요.

이렇게 하면 이전 커밋내역이 다 남기때문에 추적이 좋지 않아보입니다.

저희가 현재 사용중인 git flow 개발 방식은

새로운 작업을 시작할때면 master 브랜치에서부터 새로운 브랜치를 따서 작업을 진행하고 PR 을 올리고 하는 형태가 되어야합니다!

다음에 작업하실때는 마스터에서 브랜치를 파주시면 좋을 것 같습니다!

혹 방식이 마음에 들지 않는다거나 다른방식으로 개발을 진행하고 싶으시다면 말씀해주세요!!

2023-09-14 06:29 UTC, AdolphKim commented
마스터에서 브랜치를 판다고 팠는데 왜 이렇게 된지 잘 모르겠네요 ㅜㅜ 다음 브랜치부터 잘 해보겠습니다.

2023-09-14 12:05 UTC, AdolphKim commented
리뷰해주신 부분 모두 수정하였습니다. 확인 부탁드립니다

2023-09-17 06:40 UTC, daehwan2 reviewed
오 컴포넌트들이 다 사용성 좋게 잘만들어진것 같아요!
수고 많으셨습니다!!

2023-09-17 06:40 UTC, daehwan2 commented on components/atom/buttons/DrawerButton/index.tsx
> +import React, { useState } from 'react';
useState 가 안쓰이고 있네요!

2023-09-17 06:40 UTC, daehwan2 commented on components/atom/buttons/DrawerButton/index.tsx
> +  transform: ${({ draw }) => (draw ? 'rotateX(180deg)' : '')};
이건 일부러 
rotateX 로 하신걸까요?

2023-09-17 06:40 UTC, daehwan2 commented on components/molecule/Drawer/index.tsx
> +      <DrawBox className="DrawBox" is_draw={draw}>
className 은 안쓰이고 있는 속성같네요!

2023-09-17 06:40 UTC, daehwan2 commented on components/molecule/ReserveCardHeader/index.tsx
>    reserveKey: number;
안쓰이고 있는 것 같습니다!

2023-09-17 06:40 UTC, daehwan2 commented on components/molecule/ReserveCardMain/index.tsx
> +  align-self: center;
이건 현재 의미있는 속성일까요?

2023-09-20 08:11 UTC, AdolphKim commented on components/atom/buttons/DrawerButton/index.tsx
> +  transform: ${({ draw }) => (draw ? 'rotateX(180deg)' : '')};
회전시키는 방법이 따로 있을까요..?

2023-09-20 08:15 UTC, AdolphKim commented
코드리뷰 해주신 부분 수정하였습니다.

2023-09-20 08:52 UTC, daehwan2 commented on components/atom/buttons/DrawerButton/index.tsx
> +  transform: ${({ draw }) => (draw ? 'rotateX(180deg)' : '')};
아 제말은
그냥

rotate를 하면 회전하는 모양이 반시계인가 시계인가 방향으로 돌아가는데

rotateX를 하면, 회전하는 방향이 입체적이여서 보이지가 않거든요 의도하신건가 싶어서 코멘트 달았습니다!

2023-09-20 10:11 UTC, AdolphKim commented on components/atom/buttons/DrawerButton/index.tsx
> +  transform: ${({ draw }) => (draw ? 'rotateX(180deg)' : '')};
아 넵 제가 보기에는 X를 붙이는게 제일 스타일이 좋아보여서 그렇게 적용하였습니다. 

rotate 로 사용하기 원하시면 그렇게 하도록 하겠습니다.

2023-09-21 01:05 UTC, daehwan2 commented on components/atom/buttons/DrawerButton/index.tsx
> +  transform: ${({ draw }) => (draw ? 'rotateX(180deg)' : '')};
oh nono
i just wonder

2023-09-21 01:05 UTC, daehwan2 commented
확인완료 머지하겠습니답
수고하셨ㅅ븐디ㅏ~

2023-09-21 01:05 UTC, daehwan2 approved these changes

2023-09-21 01:05 UTC, merged